# Generated by Django 2.1.7 on 2019-05-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivobs',
            name='coach',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
