# Generated by Django 2.1.7 on 2019-05-11 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0002_auto_20190509_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivobs',
            name='joueur',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Joueur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suivobs',
            name='coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Entraineur', to=settings.AUTH_USER_MODEL),
        ),
    ]
